issuer: http://localhost:5666

mongoURI: mongodb://localhost:27018/heimdall

expiry:
  idToken: '6 hours'
  accessToken: '6 hours'

clients:
- id: heimdall-sample-app
  redirectURI: http://localhost:3000/callback
  audience:
  - heimdall-sample-api
  scopes:
  - read:messages

providers:
- type: github
  id: github
  name: GitHub
  config:
    clientId: clientId
    clientSecret: clientSecret
