issuer: http://localhost:5666

mongoURI: mongodb://localhost:27018/heimdall

sessionKey: '!!9873039&&os9d09fxlkjzc'

expiry:
  idToken: 21600
  accessToken: 21600

clients:
- id: heimdall-sample-app
  redirectURI: http://localhost:3000/callback
  audience:
  - heimdall-sample-api
  scopes:
  - read:messages

providers:
- type: github
  id: github
  name: GitHub
  config:
    clientId: clientId
    clientSecret: clientSecret
